[build]
  base = "exampleSite"
  command = "hugo --gc --themesDir ../.. -b $URL"
  publish = "exampleSite/public"

[context.production.environment]
  HUGO_VERSION = "0.74"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build.environment]
  HUGO_THEME = "repo"

[context.deploy-preview]
  command = "hugo --gc --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --themesDir ../.. -b $DEPLOY_PRIME_URL"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[redirects]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin: *